'use server';

/**
 * Creates a new payment record in the system
 * @param {Object} params - Payment creation parameters
 * @param {string} [params.type] - Payment type (GATEWAY, COD, BANK_TRANSFER, MANUAL)
 * @param {string} [params.amount] - Payment amount
 * @param {string} [params.currency] - Currency ID
 * @param {string} [params.name] - Payment name (generated by trigger if not provided)
 * @param {string} [params.status] - Payment status (PAID, UNPAID, REFUNDED), defaults to UNPAID
 * @param {string} [params.paid_at] - Timestamp when payment was paid
 * @param {string} [params.refunded_at] - Timestamp when payment was refunded
 * @param {string} [params.customer] - Customer ID
 * @param {string} params.order - Order ID
 * @param {string} [params.external_name] - External reference name/ID
 * @param {string} [params.provider_name] - Payment provider name
 * @param {string} [params.provider_status_title] - Payment provider status title
 * @param {number} [params.provider_status_code] - Payment provider status code
 * @returns {Promise<Object>} - Response containing the created payment
 */
export async function createPayment(params) {
  try {
    // Validate required fields
    if (!params.order) {
      return {
        success: false,
        error: 'Order ID is required'
      };
    }

    const response = await fetch('/server/payment/create', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(params),
    });

    const data = await response.json();
    return data;
  } catch (error) {
    return {
      success: false,
      error: error.message || 'An error occurred while creating payment'
    };
  }
} 